# Generated by Django 6.0 on 2025-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookoutlet',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
