# Generated by Django 6.0 on 2025-12-18 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_bookoutlet_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookoutlet',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookoutlet',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookoutlet',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
