# Generated by Django 6.0 on 2025-12-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0003_bookoutlet_author_bookoutlet_is_bestseller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookoutlet',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookoutlet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookoutlet',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='bookoutlet',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bookoutlet',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='bookoutlet',
            name='location',
        ),
        migrations.RemoveField(
            model_name='bookoutlet',
            name='updated_at',
        ),
    ]
