# Generated by Django 6.0 on 2025-12-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_remove_bookoutlet_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoutlet',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
