# Generated by Django 6.0 on 2025-12-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_alter_bookoutlet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookoutlet',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
