# Generated by Django 5.1.4 on 2025-12-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_bookoutlet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoutlet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
