# Generated by Django 5.1.4 on 2025-12-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_alter_bookoutlet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoutlet',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
