# Generated by Django 6.0 on 2025-12-22 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0010_alter_author_id_alter_bookoutlet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoutlet',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_outlet.author'),
        ),
        migrations.AlterField(
            model_name='bookoutlet',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
