# Generated by Django 6.0 on 2025-12-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0011_alter_bookoutlet_author_alter_bookoutlet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoutlet',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
