# Generated by Django 6.0 on 2025-12-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
